spring:
  kafka:
    bootstrap-servers:
      - ${KAFKA_SERVICE_HOST:localhost}:${KAFKA_SERVICE_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: spring-boot-producer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer
    streams:
      replication-factor: 3
      application-id: spring-boot-streams
    properties:
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${CONFLUENT-CLOUD-API-KEY}' password='${CONFLUENT-CLOUD-API-SECRET}';
      security.protocol: SASL_SSL
